# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:


# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

import sys, os
import importlib.metadata

sys.path.insert(0, os.path.abspath('.'))
sys.path.insert(0, os.path.abspath('../../src'))  # or "../../src
sys.path.append(os.path.abspath('sphinxext'))

project = 'larvaworld'
author = 'Panagiotis Sakagiannis'
copyright = '2023, Panagiotis Sakagiannis'

# The short X.Y version
version = importlib.metadata.version("larvaworld")
# The full version, including alpha/beta/rc tags
# release = ''

# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

extensions = [
    # 'recommonmark',
    # 'm2r2',
    "sphinx.ext.autodoc",  # automatically generate documentation for modules
    "sphinx.ext.napoleon",  # to read Google-style or Numpy-style docstrings
    "sphinx.ext.viewcode",  # to allow vieing the source code in the web page
    'sphinx.ext.intersphinx',
    'sphinx.ext.todo',
    'sphinx.ext.coverage',
    'sphinx.ext.mathjax',
    'sphinx.ext.ifconfig',
    'sphinx.ext.doctest',
    'sphinx.ext.duration',
    'sphinx.ext.githubpages',
    'sphinx.ext.extlinks',
    'sphinx.ext.graphviz',
    'sphinx.ext.autosummary',
    "myst_nb",
    # "myst_parser",
    # "autoapi.extension",
    'sphinx.ext.autodoc',
    'sphinx.ext.autosummary',
    # "nbsphinx",
    # "sphinx_gallery.load_style",
    # "autodocsumm",  # to generate tables of functions, attributes, methods, etc.
]

# Napoleon settings
napoleon_google_docstring = True
napoleon_numpy_docstring = True
napoleon_include_init_with_doc = True
napoleon_include_private_with_doc = True
napoleon_include_special_with_doc = True
napoleon_use_admonition_for_examples = False
napoleon_use_admonition_for_notes = False
napoleon_use_admonition_for_references = False
napoleon_use_ivar = False
napoleon_use_param = True
napoleon_use_rtype = True

source_suffix = {
    '.rst': 'restructuredtext',
    '.txt': 'restructuredtext',
    '.md': 'markdown',
}

templates_path = ['_templates']
exclude_patterns = []

# The master toctree document.
master_doc = 'index'

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'en'

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'friendly'

autoapi_generate_api_docs = True
autoapi_keep_files = True
autoapi_dirs = ["../../src/larvaworld"]  # location to parse for API reference
autoapi_root = 'api'

# don't include docstrings from the parent class
autodoc_inherit_docstrings = False
# Show types only in descriptions, not in signatures
autodoc_typehints = "description"

# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output
html_theme = "sphinx_rtd_theme"
html_static_path = ['_static']

append_material = """

.. toctree::
   :maxdepth: 2
   :caption: Examples
   :hidden:

   about-examples.rst
   examples/index
   
.. toctree::
   :maxdepth: 2
   :caption: Tutorials
   :hidden:

   tutorials/theoretical_background.ipynb
   tutorials/tutorial.ipynb
   tutorials/walkthrough.ipynb
   
   tutorials/registry.ipynb
   tutorials/model_calibration.ipynb
   tutorials/drosophila_larva_foraging.ipynb

"""

extra = """

.. toctree::
   :maxdepth: 2
   :caption: Development Guide
   :hidden:

   dev-guide/contributing
   dev-guide/repo-structure
   dev-guide/templates
   dev-guide/snippets/index
   dev-guide/resources

"""

'''


# Import the package to document:
import larvaworld
#print(larvaworld.__path__)

from gendocs import Generator
gen = Generator()
gen.DocumentPackages(larvaworld,
                     index_base='index_base.rst',
                     showprivate=True,
                     notify=False,
                     intro_pages=[
                         'readme_link',
                         #'overview/getting-started',
                         #'overview/featured',
                         #'overview/agu-2018',
                     ],
                     # append_material=append_material,
                     # extra=extra,
                    )
'''

# github_doc_root = 'https://github.com/rtfd/recommonmark/tree/master/doc/'
# def setup(app):
#     app.add_config_value('recommonmark_config', {
#             'url_resolver': lambda url: github_doc_root + url,
#             'auto_toc_tree_section': 'Contents',
#             }, True)
#     app.add_transform(AutoStructify)